model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.model_dir}/checkpoints
  filename: best
  monitor: val/loss
  mode: min
  save_top_k: 1
  save_last: true

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: epoch

metrics_writer:
  _target_: src.utils.metrics_callback.JsonMetricsWriter
  output_path: ${paths.log_dir}/metrics.json
